name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I AGREE this CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'cla/signatures/version1/cla.json'
          path-to-document: 'https://github.com/hamonikr/nimf/blob/master/cla/cla_ko.md' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'master'
          allowlist: bot*

         #below are the optional inputs - If the optional inputs are not given, then default values will be taken
          ##remote-organization-name: enter the remote organization name where the signatures should be stored (Default is storing the signatures in the same repository)
          ##remote-repository-name:  enter the  remote repository name where the signatures should be stored (Default is storing the signatures in the same repository)
          #create-file-commit-message: 'For example: Creating file for storing CLA Signatures'
          #signed-commit-message: 'For example: $contributorName has signed the CLA in #$pullRequestNo'
          custom-notsigned-prcomment: "\n\n하모니카 프로젝트에 기여해 주셔서 감사합니다! 요청해 주신 PR을 반영하기 이전에, [Contributor License Agreements](https://ko.wikipedia.org/wiki/%EA%B8%B0%EC%97%AC%EC%9E%90_%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4_%EB%8F%99%EC%9D%98)에 동의해 주셔야 합니다. [해당 문서](https://github.com/hamonikr/nimf/blob/master/cla/cla_ko.md)를 확인하신 후, 댓글로 아래 문구(I AGREE this CLA)를 남겨주시면 CLA 사인이 완료됩니다.\n\nThank you for your pull request and welcome to our community! We require contributors to sign our [Contributor License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement). After checking [this document](https://github.com/hamonikr/nimf/blob/master/cla/cla_en.md), please leave the following statement(I AGREE this CLA) in the comments to complete the CLA signature."
          custom-pr-sign-comment: 'I AGREE this CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          #lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
          #use-dco-flag: true - If you are using DCO instead of CLA

